### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by cldjq** [rjcoupe/pm_inventory_builder#1]
how do i use it ?  update README.md,Please!

**Comment by rjcoupe** [comment]
I've added the output of the `-help` flag to the README.md file. I'll add greater info eventually - at the moment this project is/was primarily for my own use so documentation wasn't a focus.

**Comment by modem7** [comment]
> how do i use it ? update README.md,Please!

@CLDJQ @rjcoupe - I've made a quick and dirty script for Docker. 

Steps required:
- Clone the repo (git clone https://github.com/rjcoupe/pm_inventory_builder.git)
- cd in repo folder
- Adjust variables in the script
- Run the script which builds the project + runs the relevant commands

```bash
#!/bin/bash

# Variables
PM_IP='192.168.1.100'
PM_PORT='8006'
PM_USER='ubuntu'
PM_TOKENID='myUser@pve!myToken'
PM_TOKENSECRET='44a2085e-f9ae-41c7-a595-d66ece971203'

# Run inventory builder
docker run --rm -e PM_IP -e PM_PORT -e PM_USER -e PM_TOKENID -e PM_TOKENSECRET -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp golang /bin/bash -c "go install -v && pm_inventory_builder -url https://$PM_IP:$PM_PORT -allow-insecure-tls -ansible-user $PM_USER -tokenId $PM_TOKENID -tokenSecret $PM_TOKENSECRET > my_proxmox_inventory.yaml"

exit 0
```

This reduces the requirement to install golang and related dependencies and outputs the file to the current directory.

Should be easy enough to create a Docker image with env vars from this, so you can run a quick oneliner and not have to worry about cloning the repo. Even for personal use it would be more streamlined.

I'd be happy to slap together a quick Dockerfile if it'd be useful?

**Comment by modem7** [comment]
I've got a working Docker version here with supporting documentation: https://github.com/modem7/pm_inventory_builder/

I've also updated the go module to 1.19 from 1.17.

**Comment by rjcoupe** [comment]
Thanks @modem7, great stuff.
